"""empty message

Revision ID: e0e971a32d7a
Revises: 2d873a1b03ca
Create Date: 2020-04-17 03:14:31.390552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e971a32d7a'
down_revision = '2d873a1b03ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('show_venue_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_venue_id_fkey', 'show', 'venue', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
